### ISSUE TITLE
Crashes when quitting

### ISSUE THREAD

**Issue by workergnome** [bakercp/ofxHTTP#11]
When running the example_basic_file_server, everything works, but when I quit the application I get:

    [warning] BaseServer_::stop: Server is not running.  Call start() to start.
    libc++abi.dylib: terminate called throwing an exception

And sometimes 

System exception: cannot lock mutex
System exception: cannot lock mutex

And then I have to force quit.

 I'm running this on a Mac, 10.8.5, via `make && make run`, on OF 0.8.0.

**Comment by bakercp** [comment]
I believe that this has been resolved with the latest Poco and better thread handling all around.  Please re-open if not resolved in the develop branch.

**Comment by workergnome** [comment]
Congrats, and thanks!
