### ISSUE TITLE
custom route handler events?

### ISSUE THREAD

**Issue by chriship** [bakercp/ofxHTTP#24]
Is it possible to set up new route handlers? For example, if I call the following url:

http://localhost:7890/test

In OF I can enable a handler for the 'test' route instead of only post?

**Comment by bakercp** [comment]
You should check out `IPVideoRoute.h`, `IPVideoRouteHandler.h` and `IPVideoRouteSettings.h` as an example.  You can configure how the route response by changing its settings (which are in the `BaseRouteSettings` class).

In the settings you can define which method is supported (POST, PUT, GET, etc).

**Comment by chriship** [comment]
Thanks, but I am a bit lost with this. Is there a simple example somewhere?

**Comment by bakercp** [comment]
Are you trying to "POST" to the http://localhost:7890/test url?

**Comment by chriship** [comment]
Thats right. I suppose I can post to http://localhost:7890/post but would
like to define different routes to post to if possible.

**Comment by bakercp** [comment]
In your setup of the POST example, perhaps try:

```
    ofx::HTTP::BasicPostServerSettings settings;

    settings.setRoutePathPattern("/test");

    // Many other settings are available.
    settings.setPort(7890);
```

**Comment by bakercp** [comment]
Marking this as closed.  Please reopen if the issue persists.
