### ISSUE TITLE
PostRequest wrong method

### ISSUE THREAD

**Issue by sheva29** [bakercp/ofxHTTP#25]
I tried testing the PostRequest method with two dumping servers. I was trying to upload a JSON object, but it wouldn't work. 

One thing that I noticed, in the two servers, is that the method that it prints on the header is PUT and not POST. I wonder if PostRequest is not inheriting the right HTTP_METHOD. Here:

http://www.posttestserver.com/data/2015/01/28/23.25.561528837370
Have you had any issues with a post request?

**Comment by bakercp** [comment]
I haven't had any issues with Post requests -- could you post some example code to demonstrate the problem?

**Comment by sheva29** [comment]
Hey Christopher,

Here is the example code I'm using. Very straight forward. 
```c++
#include "ofApp.h"
 
//--------------------------------------------------------------
void ofApp::setup(){
    
    //HTTP POST Dumping Server
    string url = "http://posttestserver.com/post.php?";
    
    ofxHTTP::DefaultClient client;
    ofxHTTP::Context context;
    
    ofxHTTP::BaseResponse response;
    ofxHTTP::PostRequest post(url);
    
    //Passing a JSON file
    post.addFormFile("people.json", "json/", "text/javascript");
    
    try
    {
        // Execute the request and get the response stream.
        std::istream& responseStream = client.execute(post,
                                                      response,
                                                      context);
        
        // Request and response headers can be examined here.
        
        // Copy the output to the terminal.
        Poco::StreamCopier::copyStream(responseStream, std::cout);
        
        // Flush the input stream.
        std::cout << std::endl;
    }
    catch(const Poco::Exception& exc)
    {
        ofLogError("ofApp::setup") << "Got Exception " << exc.displayText() << " " << exc.code();
    }
    catch(...)
    {
        ofLogError("ofApp::setup") << "Got unknown exception.";
    }
    
    
}
 
//--------------------------------------------------------------
void ofApp::update(){
    
}
 
//--------------------------------------------------------------
void ofApp::draw(){
    
}
```
The link that I included in the first post is the result from the transaction. As you can see it doesn't upload the file :(. I wonder if that server doesn't consume JSON and that might be causing the problem.

One thing that I observed was that when I used
```c++
post.addFormField("key", "value");
```
Instead of the JSON object it would go through. 

Thanks!

**Comment by sheva29** [comment]
Hey Christopher,

For some reason when I add a file. It doesn't get posted. Not sure if that method works well. I'm doing the following:

```c++
post.addFormFile("data", "json/products.json", "application/json");
```

Again I have tried in two servers but the data doesn't make it to the otherside. Have you tried that method or addFormBuffer?

**Comment by bakercp** [comment]
Please check out the updated post `JSONRequest` in the develop branch.

https://github.com/bakercp/ofxHTTP/tree/develop/example_basic_client_post_json

Marking this as resolved.
