### ISSUE TITLE
example_basic_post_server - File upload corrupts uploaded File

### ISSUE THREAD

**Issue by doktorsuarez** [bakercp/ofxHTTP#27]
Hi,
File upload process is working but this error occurs during the upload: PostRouteFileHandler::handlePart: No filename in header . 
After the upload, the file does exist in the uploads directory, but it is corrupted. Tried unsuccesfully with jpeg, gif, zip and epub. with *.cpp files, there's no problem. In Case of the other files, it's not possible to open/work with the uploaded File. I noticed, that the filesize grows with the upload. (about some bytes)!?

Win7 + openFrameworks 0.8.4 + WinCB

**Comment by doktorsuarez** [comment]
I did a EOL-Conversion of the file from Macintosh to Unix. Now, filesizes of the files are identical, also I can't see any differences of the files in a hex-editor!? But still, files are corrupted.

**Comment by doktorsuarez** [comment]
In PostRouteFileHandler.cpp , i changed line 102 from

ofFile file(newFilename, ofFile::WriteOnly);

to

ofFile file(newFilename, ofFile::WriteOnly,true);

now it works!
this sets the ofFile to binarymode. Is this a win-specific issue?

**Comment by bakercp** [comment]
It definitely sounds like it's windows-related.  OfxHTTP hasn't been tested
as heavily on Windows. Thanks for investigating. Would you mind submitting
a pull request with your fixes?

**Comment by doktorsuarez** [comment]
Yes I will do that. Have to do some github-homework first, never submitted a pull request before.
