### ISSUE TITLE
Error without https://github.com/bakercp/ofxNetworkUtils 

### ISSUE THREAD

**Issue by gabrielstuff** [bakercp/ofxHTTP#30]
Hello, 
Project looks great. I've been trying to compile : the video server camera. It needs ofxNetworkUtils.h to be compiled. 
I simply downloaded the dependency and it worked.

**Comment by bakercp** [comment]
Ah, just added that one to the readme.

002da5d9a9974d5a7022193e8fc8102a528aff48

Thanks!
