### ISSUE TITLE
basic_video_server - Firefox not able to reload image

### ISSUE THREAD

**Issue by gabrielstuff** [bakercp/ofxHTTP#31]
Hello,

firefox can perfectly handle mjpg images but the example basic_video_server seems not working in firefox. Any idea why ?

**Comment by bakercp** [comment]
No idea from your report -- can you offer some steps to reproduce?

**Comment by gabrielstuff** [comment]
Of course. Go there: http://127.0.0.1:7890/ to see the basic http demo of  `ofx::HTTP::BasicIPVideoServer` and you'll that on firefox the image / video does not refresh. On chrome of safari no issue, the video play well.

Thanks

**Comment by bakercp** [comment]
Hm.  I'm seeing video coming through on firefox, but it is choppy.  When I did the original work on it a while back, firefox was smooth, but Webkit wasn't.  I also tested it on VLC and it works.  Anyway ... this is a solid stream that I often use for testing -- it seems to work well on all browsers:

http://148.61.142.228/axis-cgi/mjpg/video.cgi?resolution=320x240

I don't have time to figure out what the difference between ofxHTTPs stream and one like this, but it would be a good place to start to better understand why it firefox gets bogged down.

If you can do some investigation, I'd appreciate it!

**Comment by bakercp** [comment]
Closing this as stale.  Please reopen if the issue persists on the develop branch.
