### ISSUE TITLE
trouble compiling websocketFrame

### ISSUE THREAD

**Issue by jmarsico** [bakercp/ofxHTTP#35]
xcode can't seem to find where .getText() comes from (i also can't determine from where this is inherited).  Xcode also complains that the constructor for `IO::ByteBuffer(buffer, size)` doesn't match anything, although this is clearly not the case. I think i'm missing something when it comes to how i've inlcuded ofxIO. I've already attempted to rebuild the project using project generator. 
xcode 6
oF 0.9.0

  any hints would be much appreciated.

**Comment by jmarsico** [comment]
problem solved. i had been using an older version of ofxIO

**Comment by bakercp** [comment]
+1 :) Yeah, been updating a bunch of stuff lately.
