### ISSUE TITLE
BaseClient::send Error with SSL URI

### ISSUE THREAD

**Issue by P0ulp** [bakercp/ofxHTTP#37]
Hello,

I noticed that when i try to use the "execute" function from the DefaultClient class, when the uri is with SSL I get the error EXC_BAD_ACCESS (code=1, address=0x0).
I have this error by using the certificate given in the "example_basic_file_server_ssl".
Maybe it's me, but if not, i hope that can help.

**Comment by bakercp** [comment]
There as an library error in the openFrameworks core recently.  Check this to see if it helps.

https://forum.openframeworks.cc/t/ofxhttp-segfault/22391/9

**Comment by P0ulp** [comment]
Thanks, it's working fine with the openFrameworks 0.9.3. !!
