### ISSUE TITLE
develop: can't build DefaultClientTask due to ofEventListener

### ISSUE THREAD

**Issue by danomatika** [bakercp/ofxHTTP#39]
On OSX 10.11.4 with OF 0.9.3

Not able to build the ofxHTTP due to unknown ofEventListener in DefaultClientTask.cpp lines 59-87. Commenting out all of the ifdefs and using the ofAddlistener/ofRemoveListener allows me to build.

**Comment by bakercp** [comment]
This is on the develop branch?

**Comment by danomatika** [comment]
Yup. Maybe ofEventListener is new to bleeding edge OF 0.9.4? I'm testing with the current 0.9.3 release as that's what my students are using.

**Comment by bakercp** [comment]
Yeah, it is a new thing.   Though, I thought I added ifdefs to get around that issue so it would be backward compatible ... cause I'm trying to get ofxHTTP develop merged with master ASAP ... 

I'm probably going to remove the taskqueue stuff from ofxHTTP before I merge it as it's becoming a little excessive now that c++11 is an option.  Anyway, I'm looking into it ...

**Comment by danomatika** [comment]
Easiest thing might be to add a version check in the ifdef.

**Comment by bakercp** [comment]
Hm ... thought I did that.  Will check.

**Comment by danomatika** [comment]
+1 for doing as much as possible with STL. Might be able to abstract away a few of your addons :)

**Comment by bakercp** [comment]
Yep.  That's the goal.

Regarding the listener thing -- I was only having compile problems on Linux so my solution was like this:

https://github.com/bakercp/ofxTaskQueue/commit/d05665cceae8ed9201eb946ee25458151144b1ee

Maybe my project was picking up older stuff and making it possible on Xcode or something, so should probably do an OF core version check instead.

**Comment by danomatika** [comment]
Version check working fine now.

**Comment by bakercp** [comment]
Cool.  I tried to get it all fixed up last night.


---
http://christopherbaker.net
