### ISSUE TITLE
send json to a url

### ISSUE THREAD

**Issue by Dazzid** [bakercp/ofxHTTP#42]
Hi!
One simple question, 
How to replicate a code like this?
$.ajax({
    method: "post",
    url: "http://seat.cpi.mialias.net/neuroconfigurador/public/json/send",
    data: { data : o }
}).done(function( resp ) {
    alert( resp );
});

I'm starting looking basic_post_server but not sure how to translate it.
Thanks

**Comment by bakercp** [comment]
See
https://forum.openframeworks.cc/t/how-to-send-as-http-post-request-as-json-in-ofx/24315/5


---
http://christopherbaker.net
