### ISSUE TITLE
ofxPoco 

### ISSUE THREAD

**Issue by juanitoddd** [bakercp/ofxHTTP#46]
Hello friends,

While trying to use the Project Generator to set up an example ( example_basic_server_file ) and after download all the ofx Addons, it keeps asking me for the ofxPoco, which I dont find anywhere.

Am I missing something out, is ofxPoco not part of the core addons ?
Thanks in advance

**Comment by bakercp** [comment]
Please check out this section of the README

https://github.com/bakercp/ofxHTTP#compatibility
