### ISSUE TITLE
having issues compiling  under linux manjaro

### ISSUE THREAD

**Issue by cyrstem** [bakercp/ofxHTTP#50]
hey  im getting this issue  not sure if it poco or what or how to fix it:

home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoNetSSL.a(Context.o):Context.cpp:function Poco::Net::Context::createSSLContext(): error: undefined reference to 'SSLv23_client_method'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoNetSSL.a(Context.o):Context.cpp:function Poco::Net::Context::createSSLContext(): error: undefined reference to 'SSLv23_server_method'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(DigestEngine.o):DigestEngine.cpp:function Poco::Crypto::DigestEngine::~DigestEngine(): error: undefined reference to 'EVP_MD_CTX_destroy'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(DigestEngine.o):DigestEngine.cpp:function Poco::Crypto::DigestEngine::reset(): error: undefined reference to 'EVP_MD_CTX_cleanup'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(DigestEngine.o):DigestEngine.cpp:function Poco::Crypto::DigestEngine::DigestEngine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&): error: undefined reference to 'EVP_MD_CTX_create'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(X509Certificate.o):X509Certificate.cpp:function Poco::Crypto::X509Certificate::extractNames(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) const: error: undefined reference to 'sk_num'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(X509Certificate.o):X509Certificate.cpp:function Poco::Crypto::X509Certificate::extractNames(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) const: error: undefined reference to 'sk_value'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'EVP_cleanup'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'ERR_free_strings'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'CRYPTO_set_locking_callback'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'CRYPTO_set_id_callback'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'SSL_library_init'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'SSL_load_error_strings'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'OPENSSL_add_all_algorithms_noconf'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_num_locks'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_locking_callback'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_id_callback'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_dynlock_create_callback'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_dynlock_lock_callback'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_dynlock_destroy_callback'
/home/jacos/OF/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'CONF_modules_free'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/jacos/OF/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:399: bin/example_advanced_client_get] Error 1
make[1]: Leaving directory '/home/jacos/OF/addons/ofxHTTP/example_advanced_client_get'
make: *** [/home/jacos/OF/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2

**Comment by bakercp** [comment]
There are a lot of poco compilation issues that can be fixed using the latest nightly or recompiling poco on the local system using apothecary.

See this for example: https://forum.openframeworks.cc/t/problem-getting-ofxhttp-to-work/32022

Since this is a poco compilation issue, I'm closing this issue and we can continue the discussion on the forum.
